// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbilitiesDisplay: typeof import('./src/components/monsterWindowComponents/AbilitiesDisplay.vue')['default']
    AbilityEntry: typeof import('./src/components/monsterWindowComponents/AbilityEntry.vue')['default']
    ActionsSidebar: typeof import('./src/components/ActionsSidebar.vue')['default']
    ActorListWindowBody: typeof import('./src/components/windowBodies/ActorListWindowBody.vue')['default']
    App: typeof import('./src/App.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    ChatMessageComponent: typeof import('./src/components/chatComponents/ChatMessageComponent.vue')['default']
    ChatToolbar: typeof import('./src/components/chatComponents/ChatToolbar.vue')['default']
    ChatWindowBody: typeof import('./src/components/windowBodies/ChatWindowBody.vue')['default']
    ComplexRoll: typeof import('./src/components/chatComponents/ComplexRoll.vue')['default']
    DefaultIcon: typeof import('./src/components/customIcons/DefaultIcon.vue')['default']
    DiceD10Icon: typeof import('./src/components/customIcons/DiceD10Icon.vue')['default']
    DiceD12Icon: typeof import('./src/components/customIcons/DiceD12Icon.vue')['default']
    DiceD20Icon: typeof import('./src/components/customIcons/DiceD20Icon.vue')['default']
    DiceD4Icon: typeof import('./src/components/customIcons/DiceD4Icon.vue')['default']
    DiceD6Icon: typeof import('./src/components/customIcons/DiceD6Icon.vue')['default']
    DiceD8Icon: typeof import('./src/components/customIcons/DiceD8Icon.vue')['default']
    DropdownComponent: typeof import('./src/components/DropdownComponent.vue')['default']
    FormOptionComponent: typeof import('./src/components/FormOptionComponent.vue')['default']
    GamePage: typeof import('./src/pages/GamePage.vue')['default']
    HeaderDisplay: typeof import('./src/components/monsterWindowComponents/HeaderDisplay.vue')['default']
    InlineRoll: typeof import('./src/components/InlineRoll.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent.vue')['default']
    ItemListWindowBody: typeof import('./src/components/windowBodies/ItemListWindowBody.vue')['default']
    MainPage: typeof import('./src/pages/MainPage.vue')['default']
    MonsterWindowBody: typeof import('./src/components/windowBodies/MonsterWindowBody.vue')['default']
    PlayArea: typeof import('./src/components/canvas/PlayArea.vue')['default']
    RemoveCloseActions: typeof import('./src/components/windowHeaderActions/RemoveCloseActions.vue')['default']
    RollResult: typeof import('./src/components/chatComponents/RollResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCloseActions: typeof import('./src/components/windowHeaderActions/SimpleCloseActions.vue')['default']
    SimpleRoll: typeof import('./src/components/chatComponents/SimpleRoll.vue')['default']
    SimpleWindowHeader: typeof import('./src/components/windowHeaders/SimpleWindowHeader.vue')['default']
    TraitsDisplay: typeof import('./src/components/monsterWindowComponents/TraitsDisplay.vue')['default']
    UploadedImage: typeof import('./src/components/chatComponents/UploadedImage.vue')['default']
    WebsocketComponent: typeof import('./src/components/WebsocketComponent.vue')['default']
    WindowActionsRender: typeof import('./src/components/windowHeaderActions/WindowActionsRender.vue')['default']
    WindowBodyRenderer: typeof import('./src/components/windowBodies/WindowBodyRenderer.vue')['default']
    WindowComponent: typeof import('./src/components/WindowComponent.vue')['default']
    WindowHeaderRenderer: typeof import('./src/components/windowHeaders/WindowHeaderRenderer.vue')['default']
  }
}
