version: "3.8"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  api:
    depends_on:
      - mongodb
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: deno-blog-api:dev
    container_name: deno-blog-api-dev
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 8000:8000
