version: "3.9"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  api:
    depends_on:
      - mongodb
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    image: deno-blog-api:dev
    container_name: api-staging
    restart: always
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend-staging
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "5000:80"
