name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup repo
#        uses: actions/checkout@v3
#
#      - name: Setup Deno
#        uses: denoland/setup-deno@v1
#        with:
#          deno-version: v1.x
#
#      - name: Deno lint
#        run: deno lint BackEnd
  deploy:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Stop docker
        run: docker compose down

      - name: Start docker
        run: docker compose up -d

      - name: Check frontend
        run: curl http://localhost:5000

      - name: Check backend
        run: sleep 5 && curl http://localhost:8000/api/
